### PR TITLE
Feature/help wanted front end final

### PR DESCRIPTION
**Pull request by miggs125**
Implemented front-end for the help wanted panel
features:
- displays assignees avatar
- displays tech stack (this needs to be updated once the backend returns an array of langauges, not just a string)
- displays repo name and issue name
- displays issue description on hover
- displays language name on icon hover
- displays github username on avatar hover

You may now roast me and my humble PR...

### CODE REVIEW

**Comment by manekenpix** [comment]
Are we still going to review this? I see this branch has conflicts.

**Comment by manekenpix** [comment]
Are we still going to review this? I see this branch has conflicts.

**Comment by miggs125** [comment]
I'll get it done this weekend

**Comment by poftadeh** [comment]
I recommend closing this PR and reopening when it's ready for review. That will trigger a new notification for reviewers when it's finished.

**Pull request closed without merging**
